const codeReset = 0;
const codeBlack = 30;
const codeRed = 31;
const codeGreen = 32;
const codeYellow = 33;
const codeBlue = 34;
const codeMagenta = 35;
const codeCyan = 36;
const codeWhite = 37;

const esc = (code: number) => `\u001B[${code}m`;
export const black = (msg: string) => `${esc(codeBlack)}${msg}${esc(codeReset)}`;
export const red = (msg: string) => `${esc(codeRed)}${msg}${esc(codeReset)}`;
export const green = (msg: string) => `${esc(codeGreen)}${msg}${esc(codeReset)}`;
export const yellow = (msg: string) => `${esc(codeYellow)}${msg}${esc(codeReset)}`;
export const blue = (msg: string) => `${esc(codeBlue)}${msg}${esc(codeReset)}`;
export const magenta = (msg: string) => `${esc(codeMagenta)}${msg}${esc(codeReset)}`;
export const cyan = (msg: string) => `${esc(codeCyan)}${msg}${esc(codeReset)}`;
export const white = (msg: string) => `${esc(codeWhite)}${msg}${esc(codeReset)}`;
export const brightBlack = (msg: string) => `${esc(codeBlack + 60)}${msg}${esc(codeReset)}`;
export const brightRed = (msg: string) => `${esc(codeRed + 60)}${msg}${esc(codeReset)}`;
export const brightGreen = (msg: string) => `${esc(codeGreen + 60)}${msg}${esc(codeReset)}`;
export const brightYellow = (msg: string) => `${esc(codeYellow + 60)}${msg}${esc(codeReset)}`;
export const brightBlue = (msg: string) => `${esc(codeBlue + 60)}${msg}${esc(codeReset)}`;
export const brightMagenta = (msg: string) => `${esc(codeMagenta + 60)}${msg}${esc(codeReset)}`;
export const brightCyan = (msg: string) => `${esc(codeCyan + 60)}${msg}${esc(codeReset)}`;
export const brightWhite = (msg: string) => `${esc(codeWhite + 60)}${msg}${esc(codeReset)}`;
export const blackBackground = (msg: string) => `${esc(codeBlack + 60)}${msg}${esc(codeReset)}`;
export const redBackground = (msg: string) => `${esc(codeRed + 10)}${msg}${esc(codeReset)}`;
export const greenBackground = (msg: string) => `${esc(codeGreen + 10)}${msg}${esc(codeReset)}`;
export const yellowBackground = (msg: string) => `${esc(codeYellow + 10)}${msg}${esc(codeReset)}`;
export const blueBackground = (msg: string) => `${esc(codeBlue + 10)}${msg}${esc(codeReset)}`;
export const magentaBackground = (msg: string) => `${esc(codeMagenta + 10)}${msg}${esc(codeReset)}`;
export const cyanBackground = (msg: string) => `${esc(codeCyan + 10)}${msg}${esc(codeReset)}`;
export const whiteBackground = (msg: string) => `${esc(codeWhite + 10)}${msg}${esc(codeReset)}`;
export const brightBlackBackground = (msg: string) => `${esc(codeBlack + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightRedBackground = (msg: string) => `${esc(codeRed + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightGreenBackground = (msg: string) => `${esc(codeGreen + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightYellowBackground = (msg: string) => `${esc(codeYellow + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightBlueBackground = (msg: string) => `${esc(codeBlue + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightMagentaBackground = (msg: string) => `${esc(codeMagenta + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightCyanBackground = (msg: string) => `${esc(codeCyan + 60 + 10)}${msg}${esc(codeReset)}`;
export const brightWhiteBackground = (msg: string) => `${esc(codeWhite + 60 + 10)}${msg}${esc(codeReset)}`;
