import * as assert from "assert";
import * as path from "path";
import { isWin } from "../../shared/constants";
import { PackageMap } from "../../shared/pub/package_map";
import { writeTempFile } from "../helpers";

const data = isWin
	? {
		originalFormat: `# Generated by pub on 2019-09-17 15:53:45.682066.
analyzer:file:///C:/analyzer/lib/
ansicolor:file:///C:/ansicolor/lib/
my_test:lib/
`,
		expectedPathFor(pkg: string) { return `C:\\${pkg}\\lib\\`; },
	}
	: {
		originalFormat: `# Generated by pub on 2019-09-17 15:53:45.682066.
analyzer:file:///analyzer/lib/
ansicolor:file:///ansicolor/lib/
my_test:lib/
`,
		expectedPathFor(pkg: string) { return `/${pkg}/lib/`; },
	};

describe.only("PackageMap", async () => {
	it(`can parse original format`, async () => {
		const file = writeTempFile(".packages", data.originalFormat);
		const map = new PackageMap(file);

		assert.deepStrictEqual(Object.keys(map.packages), ["analyzer", "ansicolor", "my_test"]);
		assert.equal(map.localPackageName, "my_test");

		assert.equal(map.getPackagePath("analyzer"), data.expectedPathFor("analyzer"));

		const sampleFilePath = path.join(data.expectedPathFor("analyzer"), "file.dart");
		assert.equal(map.convertFileToPackageUri(sampleFilePath), "package:analyzer/file.dart");
		assert.equal(map.resolvePackageUri("package:analyzer/file.dart"), sampleFilePath);
	});

	it(`can parse original format without trailing slashes`, async () => {
		const file = writeTempFile(".packages", stripTrailingSlashes(data.originalFormat));
		const map = new PackageMap(file);

		assert.deepStrictEqual(Object.keys(map.packages), ["analyzer", "ansicolor", "my_test"]);
		assert.equal(map.localPackageName, "my_test");

		assert.equal(map.getPackagePath("analyzer"), data.expectedPathFor("analyzer"));

		const sampleFilePath = path.join(data.expectedPathFor("analyzer"), "file.dart");
		assert.equal(map.convertFileToPackageUri(sampleFilePath), "package:analyzer/file.dart");
		assert.equal(map.resolvePackageUri("package:analyzer/file.dart"), sampleFilePath);
	});
});

function stripTrailingSlashes(content: string) {
	return content.replace(/\/lib\//g, "/lib");
}
