name: Build/push devcontainer image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build-devcontainer-image.yml'
  schedule:
    - cron:  '0 4 * * 1' # 4am Monday

env:
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .devcontainer
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
